apiVersion: v1
kind: Service
metadata:
  name: taiga-backend
  namespace: taiga
  labels:
    app: taiga
    role: backend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.backend.type }}
  ports:
  - name: taiga-backend
    port: {{ .Values.backend.port }}
    targetPort: 8000
    protocol: TCP
  - name: taiga-static
    port: {{ .Values.static.port }}
    targetPort: 80
    protocol: TCP
  - name: taiga-media
    port: {{ .Values.media.port }}
    targetPort: 8080
    protocol: TCP
  selector:
    app: taiga
    role: backend
