kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: taiga-media
  namespace: taiga
  labels:
    app: taiga
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
    - {{ .Values.media.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.media.storage.size | quote }}
