apiVersion: v1
kind: Namespace
metadata:
  name: taiga
  labels:
    app: taiga
    role: backend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
