apiVersion: v1
kind: Service
metadata:
  name: taiga-frontend
  namespace: taiga
  labels:
    app: taiga
    role: frontend
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.frontend.type }}
  ports:
  - name: taiga-frontend
    port: {{ .Values.frontend.port }}
    targetPort: 80
    protocol: TCP
  selector:
    app: taiga
    role: frontend
