apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
  {{- if .Values.service }}
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  {{ if .Values.service.loadBalancerIP }}loadBalancerIP: {{ .Values.service.loadBalancerIP }}{{ end }}
  {{ if .Values.service.externalIP }}
  externalIPs:
  - {{ .Values.service.externalIP }}
  {{ end }}
  selector:
    app: {{ template "fullname" . }}
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
