apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
  namespace: storage
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        role: nfs-server
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: {{ .Values.volumeName }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
