apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: storage
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
  {{ if .Values.service.clusterIP }}clusterIP: {{ .Values.service.clusterIP }}{{ end }}
